language: python

python: 3.7

cache: pip

addons:
  apt:
    packages:
      - python3-dev
      - python-dev
      - unixodbc
      - unixodbc-dev

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - make check
